### ISSUE TITLE
Codesearch model training details

### ISSUE THREAD

**Issue by lambdaofgod** [nreimers/flax-sentence-embeddings#25]
What was the hardware used for training model on CodeSearchNet? How long did it run?

Thanks in advance

**Comment by nreimers** [comment]
A TPUv3-8. Training is quick, like a few hours

**Comment by ghbacct** [comment]
@nreimers What would you say was the benefit of using a TPU?
Would it be realistic to try and train one sentence embeddings model with 1 Billion sentence pairs on a A100 GPU?
